B612 neodys tool
B612-Asteroid-Institute/astroquery pull request #1
Opened 2021-03-16 19:35 UTC by KatKiker

Testing CI

2021-03-18 19:39 UTC, carise requested changes
Mainly style issues to be consistent with astroquery. I'm using https://github.com/B612-Asteroid-Institute/astroquery/blob/master/astroquery/jplhorizons as an example.

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/__init__.py
> +from astropy import config as _config
nit: Move imports after the top docstring

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +    def query_object(self, Object_ID, OrbitElementType="Equinoctial", Epoch="Near_Middle"):
nit (here and throughout): [pep8 variables names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) should be lowercase

e.g. object_id

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +        Object_ID : string
nit: update docs to match the parameter names

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +            The Mean Julien date, and the time scale
nit: "Mean Julian" ?

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +            if Epoch == "Near_Middle":
nit: Would it make sense to create some enums for orbital_element_type and epoch so we don't have to do all this branching? We're building the same URLs, but different suffix in the form of `{orbital_element_type}{epoch}`.

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +        html_out = requests.get(Object_url, timeout=self.TIMEOUT)
super nit: as we're not parsing html, could `html_out` be named differently?

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/core.py
> +            raise RuntimeError("Page not found, check Object ID")
nit: For this `RuntimeError`, Let's just return the response status_code and text, instead of assuming that the page was not found.

2021-03-18 19:39 UTC, carise commented on astroquery/neodys/tests/test_neodys_remote.py
> +from ... import neodys
I would also recommend creating a test that uses hardcoded/local data and doesn't make actual remote calls. The example I have in mind is [jpl horizons test](https://github.com/B612-Asteroid-Institute/astroquery/blob/master/astroquery/jplhorizons/tests/test_jplhorizons.py), which uses monkeypatching for the `requests.get` (which you've probably seen).

2021-03-19 20:48 UTC, KatKiker commented on astroquery/neodys/tests/test_neodys_remote.py
> +from ... import neodys
Added in that test, and should have fixed the other issues, if you want to give it another look over.

2021-03-19 21:11 UTC, carise approved these changes
lgtm, just a few nits.

2021-03-19 21:11 UTC, carise commented on astroquery/neodys/core.py
> +        object_id : string
nit: Looking at some of the other example astroquery extensions (e.g. https://github.com/B612-Asteroid-Institute/astroquery/blob/master/astroquery/mpc/core.py) I see that the parameter types are the actual python type, e.g. "str" instead of "string".

2021-03-19 21:11 UTC, carise commented on astroquery/neodys/core.py
> +            ????
were you able to resolve what the NOR is?

2021-03-19 21:11 UTC, carise commented on astroquery/neodys/core.py
> +            raise RuntimeError(response.status_code)
Probably also a good idea to include the `response.text`.

2021-03-19 21:45 UTC, KatKiker commented on astroquery/neodys/core.py
> +            ????
I'm still waiting on that. Joachim wasn't sure and I wasn't able to find anything on the NEODyS website. I emailed them about it, but I'm pretty sure it's another Correlation matrix. Joachim explained how to calculate that from the Covariance to check, so I'm working on that now and will update once I know.

2021-03-22 21:29 UTC, merged